#tesrt
stages:
  - build
  - test
  - install

build_base:
  only:
    refs:
      - master
  stage: build
  trigger:
    project: rokkor/basejpa
    branch: master
    strategy: depend
build_base_line:
  stage: build
  only:
    refs:
      - master
  trigger:
    project: rokkor/line
    branch: master
    strategy: depend
build_base_logs:
  stage: build
  only:
    refs:
      - master
  trigger:
    project: rokkor/logdata
    branch: master
    strategy: depend
test:
  stage: test
  only:
    refs:
      - master
  tags:
    - test
  script:
    - mvn test
install:
  stage: install
  only:
    refs:
      - master
  tags:
    - install
  script:
    - mvn install -DskipTests=true
    
